---
title: "Introduction to Linear Models"
format:
  html:
    code-fold: true
jupyter: python3
---

```{python}
import os
os.chdir("..")
```


Process by which scientists, collectively and over time, endeavor to construct 
and accurate representation of the world.

1. Observation and description of a phenomenon or group of phenomena.
2. Formulation of an hypothesis to explain the phenomena.
3. Use of the hypothesis to predict the existence of other phenomena, or 
to predict wuantitatively the results of new observation.

## What is statistics?

- **Statistics** science of learning from data, and of measuring, controllig, and 
  communication uncertainty.
- Provides the navigation essential for controlling the course of scientific and 
  societal advances 

## Why become an statistician/data sciences?

- "The best thing about being a statiscian is that you get to play in everyone else's 
backyard", John Tukey, Princeton University.
- Data science combines math and statistics, specialized programming, advanced analytics, 
  artificial intilegence (AI) and machine leearning with specific subject matter expertise 
  to uncover insights in data.
- Statisticians apply statistical thinking and methods to a wide cariety of scientific, social, and business 
  endeavors in such areas as astronomy, biology, education, economics, engineering, genetics, marketing, 
  medicine. etc

## Paths in Stats

Like manyh choices in life, frequentist and bayesian.
- Statistical Theory: provides an underlying rational and provides a consistent basis for the choice of methodology.
- Applied statistics: comprises descriptive statistics and the application of inferential statistics.

## Notation and Simple Matrix Algera 

- n: numberr of distict data points, or observations, in our sample. 
- p: number of variables that are available for use.
- X: Matrix
- y: vextor

## Why linear models?

- Linear models are a fundamentals in statistics, data sciences and machine learning to understand relationships between variables.
- Linear reltionhsip between one or more indepnedant variables (predictors) and a dependent variable (reponse).
- This simplicity makes them widely applicable, interpetable, and coputationally efficient.
